FROM php:8.2-fpm

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libonig-dev

# Instalar extensiones de PHP
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Establecer el directorio de trabajo
WORKDIR /var/www

# Copiar el archivo composer.lock y composer.json
COPY composer.lock composer.json /var/www/

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Instalar dependencias de PHP
RUN composer install --no-scripts --no-autoloader

# Copiar el resto del código de la aplicación
COPY . /var/www

# Ejecutar Composer nuevamente para instalar dependencias
RUN composer install

# Copiar el script de inicio
COPY start.sh /var/www/start.sh

# Exponer el puerto 9000
EXPOSE 9000

# Usar el script de inicio
CMD ["sh", "/var/www/start.sh"]
