version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-cttkb45umphs73eg1r2g-a
      - DB_PORT=5432
      - DB_DATABASE=manoamigabdd
      - DB_USERNAME=manoamigabdd_user
      - DB_PASSWORD=SRRevuPlWmfVo0VkITjg0dcTwpyAsfe4
